# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
stages:
- stage: Build
  jobs:
  - job: GitCheckout
    steps:
      - bash: echo Git repo is checking out...
  - job: BuildBillingservice
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
- stage: Testing
  jobs:
    - job: Testing
      steps:
        - bash: echo Testing is in progress...